### ISSUE TITLE
哥们的这个工具这个是一直在跟E大更新的吗

### ISSUE THREAD

**Issue by johnyang007** [hushicai/ETF#12]
哥们的这个工具这个是一直在跟E大更新的吗？
是从哪里读的接口

**Comment by hushicai** [comment]
> 哥们的这个工具这个是一直在跟E大更新的吗？
> 是从哪里读的接口

这个不用跟E大更新，只是根据E大的策略算出来一个表格而已。
输入基金代码，从天天基金网读数据，计算网格。
